/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package autogenerated_code;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;

/**
 *
 * @author Chris
 */
public abstract class GuiApp extends javax.swing.JFrame {

  /**
   * Creates new form GuiApp
   */
  public GuiApp() {
    initComponents();
  }



  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    startButton = new javax.swing.JButton();
    restoreButton = new javax.swing.JButton();
    settingsButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    statusDisplay = new javax.swing.JTextPane();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new Dimension(645, 389));
    setMaximumSize(new Dimension(645, 389));
    getContentPane().setLayout(null);
    setResizable(false);

    startButton.setText("Start Backup");
    startButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        startButtonMouseClicked(evt);
      }
    });
    startButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        startButtonActionPerformed(evt);
      }
    });
    getContentPane().add(startButton);
    startButton.setBounds(110, 270, 110, 28);

    restoreButton.setText("Restore");
    restoreButton.setMaximumSize(new Dimension(97, 28));
    restoreButton.setMinimumSize(new Dimension(97, 28));
    restoreButton.setPreferredSize(new Dimension(97, 28));
    restoreButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        restoreButtonMouseClicked(evt);
      }
    });
    restoreButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        restoreButtonActionPerformed(evt);
      }
    });
    getContentPane().add(restoreButton);
    restoreButton.setBounds(110, 310, 110, 28);

    settingsButton1.setText("Settings");
    settingsButton1.setMaximumSize(new Dimension(97, 28));
    settingsButton1.setMinimumSize(new Dimension(97, 28));
    settingsButton1.setPreferredSize(new Dimension(97, 28));
    settingsButton1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        settingsButton1MouseClicked(evt);
      }
    });
    settingsButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        settingsButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(settingsButton1);
    settingsButton1.setBounds(110, 320, 110, 28);
    settingsButton1.setVisible(false);

    statusDisplay.setContentType("text/html");
    statusDisplay.setText("Status: Not Started");
    jScrollPane1.setViewportView(statusDisplay);

    jScrollPane1.setMaximumSize(new Dimension(330, 30));
    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(250, 290, 330, 30);

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dont_starve_small.png"))); // NOI18N
    getContentPane().add(jLabel2);
    jLabel2.setBounds(0, 0, 640, 360);

    Image img = Toolkit.getDefaultToolkit().getImage("/resources/dontstarve.ico");
    setIconImage(img);

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowActivated(WindowEvent evt) {
        formWindowActivated(evt);
      }
      public void windowOpened(WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_startButtonActionPerformed


  public void formWindowActivated(WindowEvent evt){}
  public void formWindowOpened(WindowEvent evt){}

  public abstract void startButtonMouseClicked(java.awt.event.MouseEvent evt);

  public void restoreButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restoreButtonMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_restoreButtonMouseClicked

  private void restoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_restoreButtonActionPerformed

  private void settingsButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButton1MouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_settingsButton1MouseClicked

  private void settingsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_settingsButton1ActionPerformed

//  /**
//   * @param args the command line arguments
//   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(GuiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//        //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new GuiApp().setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JLabel jLabel2;
  protected javax.swing.JScrollPane jScrollPane1;
  protected javax.swing.JButton restoreButton;
  protected javax.swing.JButton settingsButton1;
  protected javax.swing.JTextPane statusDisplay;
  protected javax.swing.JButton startButton;
  private Image myicon;
  // End of variables declaration//GEN-END:variables
}
