/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package autogenerated_code;

import java.awt.event.WindowEvent;

/**
 *
 * @author Chris
 */
public abstract class InitialPopup extends javax.swing.JDialog {

  /**
   * Creates new form InitialPopup
   */
  public InitialPopup(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    closeButton = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    statusLabel = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(365, 400));
    setMinimumSize(new java.awt.Dimension(365, 400));
    setModal(true);
    setPreferredSize(new java.awt.Dimension(360, 400));
    setResizable(false);
    getContentPane().setLayout(null);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Hey there! ");
    getContentPane().add(jLabel1);
    jLabel1.setBounds(10, 10, 100, 25);

    closeButton.setText("Close");
    closeButton.setEnabled(false);
    closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        closeButtonMouseClicked(evt);
      }
    });
    getContentPane().add(closeButton);
    closeButton.setBounds(240, 320, 100, 28);
    getContentPane().add(jSeparator1);
    jSeparator1.setBounds(0, 300, 360, 10);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("<HTML>Looks like this is your first time running the backup utility! Hold on a sec while I track down where all of the save files for Don't Starve are stored. It may take a minute or two if they're in a non-standard location, but don't worry, this step will only have to be done once!</HTML>");
    getContentPane().add(jLabel3);
    jLabel3.setBounds(10, 60, 340, 140);

    statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    statusLabel.setForeground(new java.awt.Color(255, 255, 255));
    statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    statusLabel.setText("<html>Status: <font color=ffa500>Searching</font>");
    getContentPane().add(statusLabel);
    statusLabel.setBounds(10, 250, 80, 50);

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/init_popup_med2.png"))); // NOI18N
    getContentPane().add(jLabel2);
    jLabel2.setBounds(0, 0, 360, 380);

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowActivated(WindowEvent evt) {
        formWindowActivated(evt);
      }
    });


    pack();
  }// </editor-fold>//GEN-END:initComponents

  public abstract void closeButtonMouseClicked(java.awt.event.MouseEvent evt);

  public abstract void formWindowActivated(WindowEvent evt);

//  /**
//   * @param args the command line arguments
//   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(InitialPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(InitialPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(InitialPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(InitialPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//        //</editor-fold>
//
//    /* Create and display the dialog */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        InitialPopup dialog = new InitialPopup(new javax.swing.JFrame(), true);
//        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//          @Override
//          public void windowClosing(java.awt.event.WindowEvent e) {
//            System.exit(0);
//          }
//        });
//        dialog.setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JButton closeButton;
  protected javax.swing.JLabel jLabel1;
  protected javax.swing.JLabel jLabel2;
  protected javax.swing.JLabel jLabel3;
  protected javax.swing.JLabel statusLabel;
  protected javax.swing.JSeparator jSeparator1;
  // End of variables declaration//GEN-END:variables
}
